{ lib
, stdenv
, stdenvNoCC
, fetchurl
, autoPatchelfHook
}:

# Factory CLI (`droid`) — prebuilt single-file binary from downloads.factory.ai.
# version + per-system hashes live in ./sources.json, regenerated by ./update.sh.
# x64 uses the AVX2 build; CPUs without AVX2 would need the "-baseline" variant.

let
  sources = builtins.fromJSON (builtins.readFile ./sources.json);
  src' = sources.systems.${stdenv.hostPlatform.system}
    or (throw "factory-cli: unsupported system ${stdenv.hostPlatform.system}");
in
stdenvNoCC.mkDerivation {
  pname = "factory-cli";
  version = sources.version;

  src = fetchurl {
    url = "https://downloads.factory.ai/factory-cli/releases/${sources.version}/${src'.suffix}/droid";
    inherit (src') hash;
  };

  dontUnpack = true;

  nativeBuildInputs = lib.optionals stdenv.isLinux [ autoPatchelfHook ];
  buildInputs = lib.optionals stdenv.isLinux [ stdenv.cc.cc.lib ];

  installPhase = ''
    runHook preInstall
    install -Dm755 $src $out/bin/droid
    runHook postInstall
  '';

  meta = {
    description = "Factory CLI — droid agentic coding assistant";
    homepage = "https://factory.ai";
    license = lib.licenses.unfree;
    mainProgram = "droid";
    platforms = builtins.attrNames sources.systems;
  };
}
