{ lib
, stdenv
, stdenvNoCC
, fetchurl
, runtimeShell
, glibc
, gcc-unwrapped
}:

# Factory CLI (`droid`) — prebuilt single-file binary from downloads.factory.ai.
# version + per-system hashes live in ./sources.json, regenerated by ./update.sh.
#
# droid is a Bun-compiled standalone executable: the JS payload is appended
# AFTER the ELF, with a trailer at EOF. patchelf/autoPatchelfHook rewrites the
# ELF and shifts that trailer, so Bun stops finding its payload and the binary
# degrades into the plain `bun` runtime. So on Linux we keep the binary intact
# and launch it through the nix loader with a tiny wrapper instead of patching.

let
  sources = builtins.fromJSON (builtins.readFile ./sources.json);
  src' = sources.systems.${stdenv.hostPlatform.system}
    or (throw "factory-cli: unsupported system ${stdenv.hostPlatform.system}");
  loader = if stdenv.hostPlatform.isAarch64
    then "ld-linux-aarch64.so.1"
    else "ld-linux-x86-64.so.2";
in
stdenvNoCC.mkDerivation {
  pname = "factory-cli";
  version = sources.version;

  src = fetchurl {
    url = "https://downloads.factory.ai/factory-cli/releases/${sources.version}/${src'.suffix}/droid";
    inherit (src') hash;
  };

  dontUnpack = true;

  installPhase = ''
    runHook preInstall
  '' + (if stdenv.isDarwin then ''
    install -Dm755 $src $out/bin/droid
  '' else ''
    install -Dm755 $src $out/libexec/droid
    mkdir -p $out/bin
    cat > $out/bin/droid <<EOF
    #!${runtimeShell}
    exec ${glibc}/lib/${loader} \
      --library-path ${lib.makeLibraryPath [ glibc gcc-unwrapped.lib ]} \
      $out/libexec/droid "\$@"
    EOF
    chmod +x $out/bin/droid
  '') + ''
    runHook postInstall
  '';

  meta = {
    description = "Factory CLI — droid agentic coding assistant";
    homepage = "https://factory.ai";
    license = lib.licenses.unfree;
    mainProgram = "droid";
    platforms = builtins.attrNames sources.systems;
  };
}
